
== Install and configure OpenLdap

[source,sh]
----
sudo su
cd WFCORE-2647
wfcore2647Dir="$(pwd)"
nssStoreDir="${wfcore2647Dir}/nss-store"

# optionally clean the previous attempts
systemctl stop slapd
# dnf -y remove openldap-servers openldap-clients
rm -Rf /etc/openldap/*
rm -Rf /var/lib/ldap/*

dnf -y reinstall openldap-servers openldap-clients

# or install
# dnf -y install openldap-servers openldap-clients
systemctl start slapd

slapRootPassword="nUmZW75U"
ldif="dn: olcDatabase={0}config,cn=config
changetype: modify
add: olcRootPW
olcRootPW: $(slappasswd -s "$slapRootPassword")"
echo "$ldif" | ldapadd -Y EXTERNAL -H ldapi:///

ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/cosine.ldif
ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/inetorgperson.ldif

kcOrgRootPassword="PRGM93KP"
suffix="dc=keycloak,dc=org"
ldif="dn: olcDatabase=bdb,cn=config
objectClass: olcDatabaseConfig
objectClass: olcBdbConfig
olcDatabase: bdb
olcSuffix: dc=keycloak,dc=org
olcDbDirectory: /var/lib/ldap/
olcRootDN: cn=Manager,dc=keycloak,dc=org
olcRootPW: $(slappasswd -s "$kcOrgRootPassword")
olcDbIndex: objectClass eq
olcDbIndex: cn,sn,uid pres,eq,sub
olcAccess: to attrs=userPassword
  by self write
  by anonymous auth
  by dn.base="cn=Admin,dc=keycloak,dc=org" write
  by * none
olcAccess: to *
  by self write
  by dn.base="cn=Admin,dc=keycloak,dc=org" write
  by * read"
echo "$ldif" | ldapadd -Y EXTERNAL -H ldapi:///


cat keycloak-sample-users.ldif | ldapadd -x -D "cn=Manager,dc=keycloak,dc=org" -w "$kcOrgRootPassword" -H ldapi:///

#check that it is there
ldapsearch -x -D "cn=Manager,dc=keycloak,dc=org" -w "$kcOrgRootPassword" -H ldapi:/// -b ou=People,dc=keycloak,dc=org

mkdir -p /etc/openldap/certs

cp -t /etc/openldap/certs "${nssStoreDir}"

chown -R ldap:ldap /etc/openldap/certs/*

ldif="dn: cn=config
changetype: modify
replace: olcTLSCertificateFile
olcTLSCertificateFile: openldap.local
-
replace: olcTLSVerifyClient
olcTLSVerifyClient: never"
echo "$ldif" | ldapmodify -Y EXTERNAL -H ldapi:///

# note that we have set olcTLSVerifyClient: never for now

systemctl restart slapd

# eventually check if the slapd sends the cert
openssl s_client -connect localhost:636 -CAfile "${wfcore2647Dir}/ca/certs/ca.local-cert.pem"  -msg
----

== Configure WildFly

=== `olcTLSVerifyClient: never`

Frist check whether WF can auth with `olcTLSVerifyClient: never` that we have set in the OpenLDAP config above:

[source,sh]
----

cd  WFCORE-2647
wfcore2647Dir="$(pwd)"

cd wildfly
git fetch origin
# reset to a revision known to reproduce WFCORE-2647
rev="70315ea"
git reset --hard "${rev}"
mvn clean install -DskipTests -Denforcer.skip -Dcheckstyle.skip

rm -Rf "${wfcore2647Dir}/wildfly-run"
mkdir "${wfcore2647Dir}/wildfly-run"
cp -R -t "${wfcore2647Dir}/wildfly-run" dist/target/wildfly-*/*

cp -t "${wfcore2647Dir}/wildfly-run/standalone/configuration" "${wfcore2647Dir}/openldap/${rev}-standalone.xml"

cd "${wfcore2647Dir}/wildfly-run"
chmod +x bin/standalone.sh
bin/standalone.sh
----

Visit http://localhost:9990 in browser and log in with jbrown password. It should work. Stop WildFly.

=== `olcTLSVerifyClient: demand`

Now switch to `olcTLSVerifyClient: demand`

[source,sh]
----
# as root
ldif="dn: cn=config
changetype: modify
replace: olcTLSVerifyClient
olcTLSVerifyClient: demand"
echo "$ldif" | ldapmodify -Y EXTERNAL -H ldapi:///

systemctl restart slapd


openssl s_client -showcerts -connect localhost:636 -cert ca/certs/wildfly.local-cert.pem -key ca/private/wildfly.local-key.pem -CAfile ca/certs/ca.local-cert.pem
----

Start WildFly again

[source,sh]
----
# as non-root
bin/standalone.sh -Djavax.net.debug=ssl:handshake
----

Visit http://localhost:9990 in browser again and log in with jbrown password.

Expected: jbrown password can log in.

Actual: jbrown cannot log in. There are two occurences of `*** CertificateRequest` in the log. The first one is sending the client cert

[source,sh]
----
INFO  [stdout] (management task-1) *** CertificateRequest
INFO  [stdout] (management task-1) Cert Types: RSA, ECDSA, DSS
INFO  [stdout] (management task-1) Supported Signature Algorithms: SHA256withECDSA, SHA384withECDSA, SHA512withECDSA, SHA1withECDSA, Unknown (hash:0x8, signature:0x4), Unknown (hash:0x8, signature:0x5), Unknown (hash:0x8, signature:0x6), SHA256withRSA, SHA384withRSA, SHA512withRSA, SHA1withRSA, SHA256withDSA, Unknown (hash:0x5, signature:0x2), Unknown (hash:0x6, signature:0x2), SHA1withDSA
INFO  [stdout] (management task-1) Cert Authorities:
INFO  [stdout] (management task-1) <CN=ca.local>
INFO  [stdout] (management task-1) *** ServerHelloDone
INFO  [stdout] (management task-1) Warning: no suitable certificate found - continuing without client authentication
INFO  [stdout] (management task-1) *** Certificate chain
INFO  [stdout] (management task-1) <Empty>
INFO  [stdout] (management task-1) ***
----

but the second one is apparently not sending the client cert and hence the OpenLDAP server does not accept the request and
the user `jbrown` is left unauthenticated:

[source,sh]
----
*** CertificateRequest
INFO  [stdout] (Thread-78) Cert Types: RSA, ECDSA, DSS
INFO  [stdout] (Thread-78) Supported Signature Algorithms: SHA256withECDSA, SHA384withECDSA, SHA512withECDSA, SHA1withECDSA, Unknown (hash:0x8, signature:0x4), Unknown (hash:0x8, signature:0x5), Unknown (hash:0x8, signature:0x6), SHA256withRSA, SHA384withRSA, SHA512withRSA, SHA1withRSA, SHA256withDSA, Unknown (hash:0x5, signature:0x2), Unknown (hash:0x6, signature:0x2), SHA1withDSA
INFO  [stdout] (Thread-78) Cert Authorities:
INFO  [stdout] (Thread-78) <CN=ca.local>
INFO  [stdout] (Thread-78) *** ServerHelloDone
INFO  [stdout] (Thread-78) matching alias: wildfly.local
INFO  [stdout] (Thread-78) *** Certificate chain
INFO  [stdout] (Thread-78) chain [0] = [
INFO  [stdout] (Thread-78) [
...
INFO  [stdout] (management task-1) management task-1, RECV TLSv1.2 ALERT:  fatal, bad_certificate
----


== Verify that the fix works, still with `olcTLSVerifyClient: demand`

[source,sh]
----

cd  WFCORE-2647
wfcore2647Dir="$(pwd)"

cd wildfly
git fetch origin
# reset to a revision where WFCORE-2647 is fixed
rev="a542015"
git reset --hard "${rev}"
mvn clean install -DskipTests -Denforcer.skip -Dcheckstyle.skip

rm -Rf "${wfcore2647Dir}/wildfly-run"
mkdir "${wfcore2647Dir}/wildfly-run"
cp -R -t "${wfcore2647Dir}/wildfly-run" dist/target/wildfly-*/*

# Note the always-send-client-cert="true" in the standalone.xml file
cp -t "${wfcore2647Dir}/wildfly-run/standalone/configuration" "${wfcore2647Dir}/openldap/${rev}-standalone.xml"

cd "${wfcore2647Dir}/wildfly-run"
chmod +x bin/standalone.sh
bin/standalone.sh
----

Visit http://localhost:9990 in browser and log in with jbrown password. It should work. Stop WildFly.

